version: '3.8'

services:
  proof-server:
    image: "midnightnetwork/proof-server:latest"
    command: ["midnight-proof-server --network testnet"]
    ports:
      - "6300:6300"
    environment:
      RUST_BACKTRACE: "full"