version: '3.8'

services:
  proof-server:
    container_name: 'counter-proof-server'
    image: "midnightnetwork/proof-server:latest"
    ports:
      - "6300:6300"
    environment:
      RUST_BACKTRACE: "full"