# /Users/samarthhhh/Documents/mlh-internship/BrickChain/packages/polkadot/Cargo.toml
[package]
name = "polkadot"
version = "0.1.0"
edition = "2021"

#![allow(dead_code)]

[workspace]
members = [
    ".",           # main crate at this dir
]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
anyhow = "1.0"
thiserror = "2.0.17"
tracing = "0.1"
tracing-subscriber = "0.3"
actix-web = "4.4"
actix-rt = "2.9"
sp-core = "21.0"
sp-runtime = "24.0"
hex = "0.4"
